### PR TITLE
Added Localization Support & Turkish Localization

### PR DESCRIPTION
**Pull request by NovaDiablox**
Added Localization Support & Turkish Localization

### CODE REVIEW

**Comment by MartyX5555** [comment]
Adding localization into the addon is not bad (even, i like it), but i would like to ensure every word was translatable to ensure full support. Besides, also making sure that people not having the addon also can see the translations (and not #placeholder.name.example, pointing at removing the language.Add i put in a file)

**Comment by NovaDiablox** [comment]
> Adding localization into the addon is not bad (even, i like it), but i would like to ensure every word was translatable to ensure full support. Besides, also making sure that people not having the addon also can see the translations (and not #placeholder.name.example, pointing at removing the language.Add i put in a file)

Oh for full support I didn't want to touch the code part but I can try.

**Comment by NovaDiablox** [comment]
I still insist on you to add the other lines in the code. Then I can add the remaining ones with ease.

**Comment by MartyX5555** [comment]
Yeah, i will merge your pr and expand the rest of missing areas to be translatable. After that, ofc, you could need to add the new missing areas with the turkish translation.

**Comment by MartyX5555** [comment]
@NovaDiablox the push is out. Feel free to translate the whole tool if needed. Also. as suggestion, i would recommend you keep "G-Rule" word unstranslated as thats the tool's name (and yeah, the addon name too), to let the people know the tool origin.

**Comment by NovaDiablox** [comment]
> @NovaDiablox the push is out. Feel free to translate the whole tool if needed. Also. as suggestion, i would recommend you keep "G-Rule" word unstranslated as thats the tool's name (and yeah, the addon name too), to let the people know the tool origin.

Thanks, I will keep that in mind.

**Pull request merged**
